apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{ toYaml .Values.labels | indent 4 }}
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        {{ toYaml .Values.labels | indent 8 }}
    spec:
      containers:
      - name: techtrends
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3111
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}